Neos:
  Imagine:
    driver: Imagick

  Flow:
    persistence:
      backendOptions:
        host: '%env:MYSQL_HOST%'
        dbname: '%env:MYSQL_DATABASE%'
        user: '%env:MYSQL_USER%'
        password: '%env:MYSQL_PASSWORD%'

  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: '%env:MAILHOG_HOST%'
